PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ArmyList"("Id" integer,"Name" varchar(50));
INSERT INTO ArmyList VALUES(0,'Bretonnen');
INSERT INTO ArmyList VALUES(1,'Chaos');
INSERT INTO ArmyList VALUES(2,'Horden des Chaos');
INSERT INTO ArmyList VALUES(3,'Chaoszwerge');
INSERT INTO ArmyList VALUES(4,'Dämonen');
INSERT INTO ArmyList VALUES(5,'Dunkelelfen');
INSERT INTO ArmyList VALUES(6,'Echsenmenschen');
INSERT INTO ArmyList VALUES(7,'Hochelfen');
INSERT INTO ArmyList VALUES(8,'Imperium');
INSERT INTO ArmyList VALUES(9,'Orks & Goblins');
INSERT INTO ArmyList VALUES(10,'Skaven');
INSERT INTO ArmyList VALUES(11,'Biestmenschen');
INSERT INTO ArmyList VALUES(12,'Untote');
INSERT INTO ArmyList VALUES(13,'Waldelfen');
INSERT INTO ArmyList VALUES(14,'Zwerge');
COMMIT;
