PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ArmyList"("Id" integer,"Name" varchar(50));
INSERT INTO ArmyList VALUES(0,'Bretonnia');
INSERT INTO ArmyList VALUES(1,'Chaos');
INSERT INTO ArmyList VALUES(2,'Hordes of Chaos');
INSERT INTO ArmyList VALUES(3,'Chaos Dwarfs');
INSERT INTO ArmyList VALUES(4,'Demons');
INSERT INTO ArmyList VALUES(5,'Dark Elves');
INSERT INTO ArmyList VALUES(6,'Lizardmen');
INSERT INTO ArmyList VALUES(7,'High Elves');
INSERT INTO ArmyList VALUES(8,'Empire');
INSERT INTO ArmyList VALUES(9,'Orcs & Goblins');
INSERT INTO ArmyList VALUES(10,'Skaven');
INSERT INTO ArmyList VALUES(11,'Beasts of Chaos');
INSERT INTO ArmyList VALUES(12,'Undead');
INSERT INTO ArmyList VALUES(13,'Wood Elves');
INSERT INTO ArmyList VALUES(14,'Dwarfs');
COMMIT;
